#!/usr/bin/env escript
%%! -smp disable -sname run
% vim: ft=erlang
-mode(native).

main([File, BestFile]) -> main([File, BestFile, 50]);
main([File, BestFile, Base]) -> main([File, BestFile, Base, 2]);
main([File, BestFile, Base, Islands]) ->
  main([File, BestFile, Base, Islands, 1000]);
main([File, BestFile, Base, Islands, Time]) ->
  main([File, BestFile, Base, Islands, Time, 5]);
main([File, BestFile, Base, Islands, Time, Mutability]) ->
  main([File, BestFile, Base, Islands, Time, Mutability, 2]);
main([File, BestFile, Base, Islands, Time, Mutability, Meeting]) ->
  genetic:start(File, BestFile, parse_number(Base), parse_number(Islands),
    parse_number(Time), parse_number(Mutability), parse_number(Meeting)),
  halt(0);

main(_) ->
  usage(),
  halt(0).

usage() ->
  io:format("usage: run FILE BEST_FILE [BASE_SIZE [ISLANDS [TIME_LEFT [MUTABILITY]]]]~n").

parse_number(Int) when is_integer(Int) -> Int;
parse_number(Str) when is_list(Str) -> parse_number(list_to_integer(Str));
parse_number(Bin) when is_binary(Bin) -> parse_number(binary_to_list(Bin)).

