#!/bin/bash

#for size in 50 100 200; do
#  for t in 1000 5000 10000; do
#    for i in 1 2 3; do
#      ./run samples/dane40g.txt samples/optymalne40g.txt $size $t 2 | tee "results/40_${size}_${t}_2_${i}.txt";
#    done
#  done
#done

for size in 50 100 200; do
  for t in 1000 5000 10000; do
    for i in 1 2 3; do
      ./run samples/dane50g.txt samples/optymalne50g.txt $size $t 2 | tee "results/50_${size}_${t}_2_${i}.txt";
    done
  done
done

#for size in 50 100 200; do
#  for t in 1000 5000 10000; do
#    for i in 1 2 3; do
#      ./run samples/dane100g.txt samples/optymalne100g.txt $size $t 2 | tee "results/100_${size}_${t}_2_${i}.txt";
#    done
#  done
#done

